### ISSUE TITLE
Attributes of type Base64Bytes or bytes should be base64 encoded

### ISSUE THREAD

**Issue by pbouda** [python-scim/scim2-tester#13]
I think attributes that are defined as `binary` in the RFC 7643 (in Python code formerly `bytes` and now `Base64Bytes` as far as I can see, for example https://github.com/python-scim/scim2-models/blob/main/scim2_models/rfc7643/user.py#L212) should be send as base64 encoded strings: https://datatracker.ietf.org/doc/html/rfc7643#section-2.3.6

Right now the random value that gets generated and sent is just a UUID, e.g. `72fd1c53-83f8-4b2d-8125-df887df4e617`.

I don't know if this works with the latest code that has `Base64Bytes` as I currently get an error with the scim2-tester main branch:

```
Traceback (most recent call last):
  File "C:\Users\pboud\Projects\scim2-tester\scim2_tester\checker.py", line 101, in <module>
    results = check_server(scim)
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\pboud\Projects\scim2-tester\scim2_tester\checker.py", line 81, in check_server
    check_resource_type(scim, resource_type, service_provider_config)
  File "C:\Users\pboud\.pyenv\pyenv-win\versions\3.12.4-arm\Lib\site-packages\scim2_tester\resource.py", line 203, in check_resource_type
    fill_with_random_values(obj)
  File "C:\Users\pboud\.pyenv\pyenv-win\versions\3.12.4-arm\Lib\site-packages\scim2_tester\resource.py", line 60, in fill_with_random_values
    fill_with_random_values(value)
  File "C:\Users\pboud\.pyenv\pyenv-win\versions\3.12.4-arm\Lib\site-packages\scim2_tester\resource.py", line 55, in fill_with_random_values
    elif issubclass(field_type, Enum):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
```

Where `field_type` is `typing.Annotated[bytes, EncodedBytes(encoder=<class 'pydantic.types.Base64Encoder'>)]`.

**Comment by azmeuk** [comment]
Thank you for your report.
This is fixed in 0.1.10
